Repository k8-proxy/p-k8-jmeter-test-engine, pull requests merged in 2020-10, with the labels that each got.

#21 Jmeter report
  upwork-devs/harut.grigoryan/controlling-jmeter-pod/docker-jmeter-c-icap/Test/launch.sh
  upwork-devs/harut.grigoryan/controlling-jmeter-pod/docker-jmeter-c-icap/processor.py
Labels: FEATURE-592

#26 Install Prometheus to k8s using github actions
  .github/workflows/deploy_common_res.yaml
  kubernetes/common_resources/README.md
Labels: ready-to-review

#38 GitHub actions to build and push jmeter-icap docker image
  .github/workflows/README.md
  .github/workflows/docker_ci.yaml
  .github/workflows/run_tests.yaml
  .gitignore
  kubernetes/common_resources/README.md
Labels: ready-to-review

#35 Update README with deployment instructions and steps to integrate minio with jmeter k8s jobs
  .github/workflows/docker_ci.yaml
Labels: ready-to-review

#42 fix permissions for shell script
  src/controller/docker-jmeter-c-icap/Dockerfile
  src/controller/docker-jmeter-c-icap/icap.jmx
  src/controller/docker-jmeter-c-icap/jmeter-job-tmpl.yaml
Labels: ready-to-review

#48 Price estimation for tests in AKS
  utils/pricing_estimate.xlsx
Labels: ready-to-review

#52 Create persistent volumes for minio and grafana k8s deployments
  kubernetes/common_resources/grafana.yaml
  kubernetes/common_resources/minio.yaml
Labels: ready-to-review

#54 Commit issue #15 Health check monitoring of the icap-serve
  upwork-devs/Son-Ha/FetchICAP_Server_metrics.jmx
  upwork-devs/Son-Ha/Readme.md
Labels: ready-to-review

#71 Pass JVM_ARGS with manifest definitions
  src/controller/docker-jmeter-c-icap/ICAP-POC_s3.jmx
  src/controller/docker-jmeter-c-icap/Makefile
  src/controller/docker-jmeter-c-icap/Test/launch.sh
  src/controller/docker-jmeter-c-icap/jmeter-job-tmpl.yaml
Labels: ready-to-review

#72 Add deployment of Loki to github actions
  .github/workflows/deploy_common_res.yaml
  .github/workflows/docker_ci.yaml
  kubernetes/common_resources/README.md
Labels: ready-to-review

#79 add initialization script for influxdb
  .github/workflows/deploy_common_res.yaml
  kubernetes/common_resources/README.md
  kubernetes/common_resources/influxdb/influxdb.yaml
  kubernetes/common_resources/influxdb/init-influxdb.iql
Labels: ready-to-review

#83 Have capability to scale minio pods with own shared storage #80
  kubernetes/shared_storage_minio_pods/README.md
  kubernetes/shared_storage_minio_pods/azure-file-storage-pvc.yaml
  kubernetes/shared_storage_minio_pods/azure-file-storage.yaml
  kubernetes/shared_storage_minio_pods/minio_deploy.yaml
Labels: ready-to-review

#84 Closes #77
  src/controller/recommendations.md
Labels: ready-to-review

#101 Eks terraform
  terraform/eks/README.md
  terraform/eks/eks-cluster.tf
Labels: ready-to-review

#102 Docker Images
  Dockerfiles/README.md
  Dockerfiles/jmeter-base
  Dockerfiles/jmeter-testdata
Labels: ready-to-review

#91 Issue 68
  src/s3-to-minio/README.md
  src/s3-to-minio/files.csv
  src/s3-to-minio/s3-to-minio.py
Labels: Changes requested, P1, ready-to-review

#107 Persistance storage multipod for Minio and InfluxDB
  kubernetes/common_resources/influxdb/influxdb.yaml
  kubernetes/common_resources/minio.yaml
  kubernetes/shared_storage_minio_pods/README.md
  kubernetes/shared_storage_minio_pods/azure-file-storage-pvc.yaml
  kubernetes/shared_storage_minio_pods/minio_deploy.yaml
  kubernetes/storage_classes/README.md
  kubernetes/storage_classes/azure-file-storage.yaml
  src/controller/docker-jmeter-c-icap/ICAP-POC_s3.jmx
Labels: Ready for review

#99 Create ICAP-POC_s3_k8.jmx
  src/controller/docker-jmeter-c-icap/ICAP-POC_s3_k8.jmx
Labels: Changes requested

#109 Helm Charts
  Dockerfiles/README.md
  helm-charts/README.md
  helm-charts/common-resources/.helmignore
  helm-charts/common-resources/Chart.yaml
  helm-charts/common-resources/README.md
  helm-charts/common-resources/aws.yaml
  helm-charts/common-resources/azure.yaml
  helm-charts/common-resources/configs/config.toml
  helm-charts/common-resources/configs/init-influxdb.toml
  helm-charts/common-resources/templates/_helpers.tpl
  helm-charts/common-resources/templates/grafana-service.yaml
  helm-charts/common-resources/templates/grafana-storage.yaml
  helm-charts/common-resources/templates/grafana.yaml
  helm-charts/common-resources/templates/influxdb-config.yaml
  helm-charts/common-resources/templates/influxdb-service.yaml
  helm-charts/common-resources/templates/influxdb-storage.yaml
  helm-charts/common-resources/templates/influxdb.yaml
  helm-charts/common-resources/templates/ingress.yaml
  helm-charts/common-resources/templates/minio-hpa.yaml
  helm-charts/common-resources/templates/minio-service.yaml
  helm-charts/common-resources/templates/minio-storage.yaml
  helm-charts/common-resources/templates/minio.yaml
  helm-charts/common-resources/templates/secrets.yaml
  helm-charts/common-resources/templates/serviceaccount.yaml
  helm-charts/common-resources/templates/tests/test-connection.yaml
  helm-charts/jmeter-test/.helmignore
  helm-charts/jmeter-test/Chart.yaml
  helm-charts/jmeter-test/configs/file.toml
  helm-charts/jmeter-test/configs/jmeter-conf.toml
  helm-charts/jmeter-test/templates/_helpers.tpl
  helm-charts/jmeter-test/templates/configmap.yaml.bak
  helm-charts/jmeter-test/templates/deployment.yaml
  helm-charts/jmeter-test/templates/ingress.yaml
  helm-charts/jmeter-test/templates/secrets.yaml
  helm-charts/jmeter-test/templates/service.yaml
  helm-charts/jmeter-test/templates/serviceaccount.yaml
  helm-charts/jmeter-test/templates/tests/test-connection.yaml
  helm-charts/jmeter-test/values.yaml
  terraform/eks/eks-cluster.tf
Labels: ready-to-review

#110 A coding correction in S3 to minio copy script
  src/s3-to-minio/s3-to-minio.py
Labels: ready-to-review

#114 Jvm Args fix
  helm-charts/README.md
  helm-charts/jmeter-test/configs/jmeter-conf.toml
  helm-charts/jmeter-test/templates/deployment.yaml
Labels: ready-to-review

#118 Task:-104 :- Implement the mechanism to dynamically create k8 pods based on the number of users.pods deployment by python script.
  eks_app_dep.py
Labels: ready-to-review

#126 update grafana version
  helm-charts/common-resources/aws.yaml
  kubernetes/common_resources/grafana.yaml
Labels: Ready-for-review

#127 Enable Spot Instances for EKS
  terraform/eks/eks-cluster.tf
  terraform/eks/variables.tf
  terraform/eks/vpc.tf
Labels: ready-to-review
